title: Clayton Stout | Staff Backend Engineer
email: clayfstout@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Staff Backend Engineer with 11+ years of experience in JVM technologies,
  specializing in Java, Kotlin, and Scala development. Welcome to my personal 
  portfolio highlighting side projects and a collection of random musings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cfstout.github.io"
github_username:  cfstout
linkedin_username: clayton-stout-91098666

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

highlighter: rouge

social:
  github: "https://github.com/cfstout"
  linkedin: "https://www.linkedin.com/in/clayton-stout-91098666"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
